### ISSUE TITLE
Integrate page won't sync up binding details while switching between bindings.

### ISSUE THREAD

**Issue by SimonGuo009** [ehamai/AzureFunctionsPortal#3]
Repro steps:
1. Create an HttpTrigger function.
2. Open Integrate page, verify trigger info opened as default.
3. Click the output binding, verify below info didn't updated.

Below snapshot is under another circumstance, but shows same problem.

![bindinginfoupdate](https://cloud.githubusercontent.com/assets/18321627/23252987/ca73b2a8-f9ed-11e6-8cd0-70595971c648.png)

**Comment by ehamai** [comment]
Fixed
