### ISSUE TITLE
Create function page should not be closed after connection created.

### ISSUE THREAD

**Issue by SimonGuo009** [ehamai/AzureFunctionsPortal#4]
Expected result:
The create function page should keep opening after connection created.

Actual result:
The page refreshed and get back to function app details page after connection created.

Repro steps:
1. Click "+" to open create function page.
2. Click EventHubTrigger - C#.
3. Click the "new" link next to Event Hub Connection dropdown.
4. Click add connection string, fill all required fields then click OK.
5. Verify page refreshed and get back to function app details page.

**Comment by ehamai** [comment]
This is fixed.
