### ISSUE TITLE
Switch between templates, template info do not sync up

### ISSUE THREAD

**Issue by SimonGuo009** [ehamai/AzureFunctionsPortal#5]
Repro steps:
1. Click + to open create function page.
2. Click ServiceBusTopic-JS template, verify its details appears below the template picker.
3. Click ManualTrigger-JS template, verify the template details did not synced up.

Please refer to below snapshot.
![templateinfodonotsyncup](https://cloud.githubusercontent.com/assets/18321627/23253503/c9d9e9a0-f9ef-11e6-8f68-133dd971cc4d.png)

**Comment by ehamai** [comment]
This is fixed.
