### ISSUE TITLE
Unable to update runtime version.

### ISSUE THREAD

**Issue by SimonGuo009** [ehamai/AzureFunctionsPortal#6]
Please refer to the snapshot.
![unabletoupdatefunctionruntimeversion](https://cloud.githubusercontent.com/assets/18321627/23253546/ed262f04-f9ef-11e6-8c4d-9c42e80ca953.png)

**Comment by ehamai** [comment]
This functionality hasn't been implemented yet.  But I should be able to get to it soon.

**Comment by ehamai** [comment]
This is fixed.
